### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by felipegs** [logstash-plugins/logstash-input-kafka#124]
Hi, 
CPU average usage is 50% processing no events, if I remove kafka input it is ok.
- Version: Logstash 5 alpha 5,
- Operating System: Amazon Linux 2015
-  Config File:
  
  ```
  kafka {
    bootstrap_servers => "**"
    ssl => true
    ssl_keystore_location => "/home/felipe.santos/client.keystore.jks"
    ssl_keystore_password => "changeit"
    ssl_truststore_location => "/home/felipe.santos/client.truststore.jks"
    ssl_truststore_password => "changeit"
    topics => ["zupme-gateway"]
    codec => "json"
  }
  .....
  ```

```
```

**Comment by talevy** [comment]
@felipegs thanks for the report. will investigate

**Comment by lin-zhao** [comment]
I ran into similar issue, but with 100% CPU without any event. Attaching stack trace.
[stack.txt](https://github.com/logstash-plugins/logstash-input-kafka/files/523248/stack.txt)

**Comment by alesnav** [comment]
Hello,

I'm adding more info to this issue...

- Version: logstash-input-kafka 5.0.5 / 6.0.0 + logstash 5.0.0
- Operating System: CentOS 7.2.1511
- Config File:
```
input {
  kafka {
    bootstrap_servers => "server1:9092,server2:9092"
    topics => ["events"]
    codec => "json"
  }
}
```

- Sample Data: N/A
- Steps to Reproduce: just start logstash service...

Hello,

I use Kafka input plugin to retrieve all events from my Logstash indexer instance. Right now, I am testing version 5.0.0 of Logstash in a non-production environment (~5 EPS... yes, only five per second).

This is the result of `top`:

```
# top
top - 09:51:20 up 16:15,  1 user,  load average: 1.54, 1.12, 0.53
Tasks: 170 total,   2 running, 168 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13.6 us,  1.0 sy,  0.0 ni, 85.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8011460 total,  3624800 free,  3118732 used,  1267928 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  4579620 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 8558 logstash  20   0 3659396 491940  14944 S 126.7  6.1   1:56.48 java
[...]
```

And these are the PID subprocesses:

```
# top -Hp 8558
top - 09:56:10 up 16:20,  1 user,  load average: 1.18, 1.17, 0.71
Threads:  32 total,   1 running,  31 sleeping,   0 stopped,   0 zombie
%Cpu(s): 53.9 us,  4.2 sy,  0.0 ni, 41.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8011460 total,  3610404 free,  3133148 used,  1267908 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  4565284 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 8604 logstash  20   0 3659396 506484  15000 R 90.0  6.3   5:32.46 [main]<kafka
 8585 logstash  20   0 3659396 506484  15000 S  9.6  6.3   0:36.18 java
 8582 logstash  20   0 3659396 506484  15000 S  6.0  6.3   0:22.02 java
 8581 logstash  20   0 3659396 506484  15000 S  5.6  6.3   0:22.10 java
 8584 logstash  20   0 3659396 506484  15000 S  3.0  6.3   0:10.20 java
 8589 logstash  20   0 3659396 506484  15000 S  0.3  6.3   0:15.35 java
[...]
```

If I add one more topic to its configuration, it starts a new thread with the same amount of CPU resources, although the second topic is empty. So, this is not a problem related to the amount of data incoming but a problem related to the connection to Kafka.

I tested this configuration using logstash-input-kafka version 5.0.5 (shipped with default logstash installation) and then, I updated this component to the last version (6.0.0 -> `bin/logstash-plugin install --version 6.0.0 logstash-input-kafka`) with the same final result.

Thanks,
Best regards

**Comment by boernd** [comment]
The issue seems to be that no default value for `poll_timeout_ms` is set when the client starts consuming:
```
kafka.rb line 202:
records = consumer.poll(poll_timeout_ms);
```

Setting a value (100ms is an example in the kafka api docs) in the logstash config fixes the cpu issue for me.

**Comment by talevy** [comment]
thank you, will fix this!

**Comment by alesnav** [comment]
Yes! It fixes the issue, from 200% to ~18% in my personal case!

I have just set that value in my kafka input config:


```
input {
  kafka {
    bootstrap_servers => "server1:9092,server2:9092"
    topics => ["events"]
    codec => "json"
    poll_timeout_ms => 100
  }
}
```

Thanks @boernd 👍

**Comment by lin-zhao** [comment]
Thanks for the fix!

**Comment by jgq2008303393** [comment]
+1
