### ISSUE TITLE
Bump to use Kafka client 0.10.0.1

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#125]
This is to track our upgrade of the input to support the latest Kafka 0.10.0.1.

https://archive.apache.org/dist/kafka/0.10.0.1/RELEASE_NOTES.html
eg. This is a good one to have (https://issues.apache.org/jira/browse/KAFKA-3879)

**Comment by suyograo** [comment]
5.0.4 published
