### ISSUE TITLE
NoMethodError: undefined method `push' for nil:NilClass

### ISSUE THREAD

**Issue by artursmolarek** [logstash-plugins/logstash-input-kafka#130]
I'm not able to run logstash with logstash-input-kafka plugin.

This is error log from my docker:

`logstash_1       | {:timestamp=>"2016-09-18T15:31:10.948000+0000", :message=>"Pipeline aborted due to error", :exception=>"LogStash::ConfigurationError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.9/lib/logstash/inputs/kafka.rb:127:in`register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:330:in `start_inputs'", "org/jruby/RubyArray.java:1613:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:329:in `start_inputs'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:180:in`start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in`start_pipeline'"], :level=>:error}
logstash_1       | {:timestamp=>"2016-09-18T15:31:13.953000+0000", :message=>"stopping pipeline", :id=>"main"}
logstash_1       | {:timestamp=>"2016-09-18T15:31:13.980000+0000", :message=>"An unexpected error occurred!", :error=>#<NoMethodError: undefined method `push' for nil:NilClass>, :class=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.9/lib/logstash/inputs/kafka.rb:171:in `stop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/inputs/base.rb:83:in`do_stop'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:385:in`shutdown'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:413:in `stop_pipeline'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:406:in`shutdown_pipelines'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:406:in`shutdown_pipelines'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:402:in `shutdown'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:233:in`execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}`

My logstash input config:

`input {
        kafka {
        }
}`

**Comment by artursmolarek** [comment]
This issue can be closed. I didn't notice that I have to set at least one of: topic_id, white_list or black_list.

**Comment by talevy** [comment]
glad to see this was resolved for you, but it should have really caught that requirement up front so that you wouldn't get a NoMethodError.

I will leave this open until we modify the startup of the plugin to check the appropriate settings were set, and provide a meaninful error message

**Comment by talevy** [comment]
Closing due to an update in the client and how topics are managed using the `topics` and `topics_pattern` configuration options.
