### ISSUE TITLE
ES Version in compatibility matrix

### ISSUE THREAD

**Issue by shaharmor** [logstash-plugins/logstash-input-kafka#131]
- Version: All
- Operating System: N/A

Hi,
I'm not sure if its needed or not, but do all Logstash versions support all Elasticsearch versions? If not, can you please list which range of version is supported per Logstash version?

I was wondering if i can just upgrade Logstash & Kafka, while keeping my ES 1.5 cluster, or i need to upgrade ES as well.

Thanks

**Comment by pickypg** [comment]
The nice thing about Logstash is that its plugins control their dependencies. The only relevant dependency for ES is when using an ES plugin (input, filter, or most likely output).

Logstash 2.x, for the Elasticsearch output, uses the HTTP handler by default, which is backwards compatible with ES 1.x and you can safely upgrade Logstash without upgrading ES.

I strongly recommend that you upgrade to a later version of ES 1.x (at least ES 1.7), if not ES 2.4.x. Not only are there performance reasons, but there's also consistency reasons as well.

**Comment by talevy** [comment]
hey @shaharmor, I hope @pickypg's answer helped you out! Closing this issue because I feel like this is a question better suited for discuss.elastic.co.
