### ISSUE TITLE
Logstash - Reading from Kafka and Inserting into ElasticSearch cluster - kafka topic lag not going down

### ISSUE THREAD

**Issue by narendra-agashe** [logstash-plugins/logstash-input-kafka#140]
Team,

My ELK stack is as follows
ES Version :- 2.3.5 (3 servers, 2 Master Eligible nodes and 1 Client, where Logstash is pointed to for inserting messages into ES)
Kafka :- 0.8 (Cluster of 3) topic has 3 partitions.
Logstash :- 2.3.4

at the moment my logstash-topic.conf looks something like this

```
input {
kafka { 
topic_id => "TopicTest"
zk_connect => "x.x.x.x:yyyy, x.x.x.x:yyyy, x.x.x.x:yyyy"
group_id => "FCA" 
auto_offset_reset => "smallest"
} 
}


output { 
elasticsearch{hosts => ["x.x.x.x:yyyy"]} // pointed to the client node in the ES cluster
}
```

originally we had not given group_id and were using default group_id, when i restarted the logstash thru supervisorctl somehow it stopped reading data from kafka. i kept on seeing lag on the topic in kafka manager. then I set  auto_offset_reset still the lag did not go down and similarly i did not see messages from that time period in my elastic search. then i added the group_id this made sure all new messages are going thru but the stacked messages are not getting read.

Originally we had single node ES which i converted to multi-node es cluster and never really thought that i will be posed problems from kafka-logstash input.  

other than above puzzle my question is when we go in PR environment should we use default group_id "logstash" by not specifying any group_id or each kafka topic should have its own group_id, the way I have given? 

Thanks,
Naren

**Comment by vinaygulani1** [comment]
I am also facing the similar issue:

It seems that the topics which are having high rate of data is not being consumed properly.
- As soon as the topic is created the data is consumed for some time with the recent timestamp.
- After some time consumer suddenly stops consuming the data  as the consumer offset stops increasing on kafka-manager. But at the same time if we look at kibana, it shows that the messages are increasing for the previous time and those messages are mostly duplicate.

Please suggest if you have found any work around for this.

**Comment by bquartier** [comment]
@vinaygulani1 I suspect we are facing the same issue.
Did you find a work around?

**Comment by vinaygulani1** [comment]
It was because the number of worker threads at indexer side were not enough to consume it. You might want to increase the worker threads for indexer. it should be multiple of number of cpu cores on indexer hosts.

add argument "pipeline-workers" at indexer like "--pipeline-workers 144"

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!

**Comment by nkaravias** [comment]
Shouldn't this be a bug? Why did it get closed? It sounds like if logstash is hitting a performance bottleneck it starts duplicating records from kafka. I've had the same issue with a similar setup this week. We need to be able to understand when logstash is hitting the point where duplication occurs. Right?

**Comment by guyisra** [comment]
any updates on this? I also get duplicates. What is the solution for this? @suyograo

**Comment by nkaravias** [comment]
A workaround is to manually fingerprint each log that is consumed from kafka. Try this: https://www.elastic.co/blog/logstash-lessons-handling-duplicates

Ideally we shouldn't have to do this however

**Comment by nagonzalez** [comment]
Totally agree. I'm seeing this issue as well and it's totally frustrating.

**Comment by jimzwli** [comment]
Fully agree. It is totally frustrating. And it is obviously a bug of plugin and not just the configuration problem. This issue does not happen for small data, but when the number of message increases in kafka topic, the plugin only returns duplicates and does read from new offset. I don't understand why close this issue!
