### ISSUE TITLE
Logstash 5.0, downgraded kafka to 4.10. Could not find plugin name kafka

### ISSUE THREAD

**Issue by smalenfant** [logstash-plugins/logstash-input-kafka#149]
I posted to discuss forums but no answer so far. 

I followed all instructions to downgrade kafka input plugin to support my Kafka 0.9.x cluster. Although seems like logstash won't find the downgraded plugin.

```
bin/logstash-plugin remove logstash-input-kafka
bin/logstash-plugin install --version 4.1.0 logstash-input-kafka
Validating logstash-input-kafka-4.1.0
Installing logstash-input-kafka
Installation successful
```

Version: logstash (5.0.0) and logstash-input-kafka (4.1.0)

Operating System: Centos 7.2

Config File:

```
input {
  kafka {
    topic_id => "test_topic"
    group_id => "test_group"
    zk_connect => "host01:2181,host02:2181,host03:2181"
    consumer_threads => 8
  }
}
```

Error:

```
:reason=>"Couldn't find any input plugin named 'kafka'. Are you sure this is correct? Trying to load the kafka input plugin resulted in this error: Problems loading the requested plugin named kafka of type input."}
```

**Comment by talevy** [comment]
@smalenfant 

there was an issue with the publishing of this version, mind trying version `4.1.1`?

```
bin/logstash-plugin install --version 4.1.1 logstash-input-kafka
```

**Comment by smalenfant** [comment]
I should have put in this issue last week! I'm not getting the `Couldn't find any input plugin named 'kafka'` anymore with 4.1.1. Thanks!
