### ISSUE TITLE
OOME When trying to plug Logstash without SSL to Kafka with SSL

### ISSUE THREAD

**Issue by gquintana** [logstash-plugins/logstash-input-kafka#153]
- Version: Logstash 2.4 + Logstash Input Kafka 5.1 or 4.x (tested both)
- Config File:
```
input {
  kafka {
    topics => ["test_topic"]
    bootstrap_servers => "kafka1:9093,kafka2:9093"
    group_id => "test_group"
    codec => json
    type => "test_type"
    # security_protocol => "SSL"
    ssl_truststore_location => "truststore.jks"
    ssl_truststore_password => "xxxxx"
  }
}
output {
  stdout {
    codec => rubydebug {}
  }
}
```
- Steps to Reproduce:
  - Kafka brokers are listening on port 9093 with SSL protocol
  - Logstash tries to connect 9093 port without the option to enable SSL
  - Logstash dies with OOME
```
Settings: Default pipeline workers: 8
Pipeline main started
java.lang.OutOfMemoryError: Java heap space
Dumping heap to $LS_HOME/heapdump.hprof ...
Unable to create $LS_HOME/heapdump.hprof: No such file or directory
Pipeline main has been shutdown
Error: Your application used more memory than the safety cap of 1G.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
```

Logstash is probably endlessly trying to reconnect and not freeing resources.
An error message telling that Logstash couldn't connect to Kafka is a must have.

**Comment by jordansissel** [comment]
@suyograo @talevy any ideas on this one?

**Comment by gquintana** [comment]
After some more testing, the OOME is not related to SSL, but I can not find the root cause.
You'll find Heap Dumps in Elastic support case #00107531

**Comment by talevy** [comment]
nothing immediate, @gquintana -- do you know that Kafka is not running and/or Zookeeper is down?

**Comment by gquintana** [comment]
No Zookeeper and Kafka were up and running.

**Comment by gquintana** [comment]
It also occurs on Logstash 2.3.4+Logstash Input Kafka 3.0.3 when I forget to add `ssl => true` while the Kafka server switched to SSL.
Yet it is not easily reproducible: sometimes Logstash starts but can doesn't connect to Kafka (as expected), sometimes Logstash dies during startup with OOME.

**Comment by gquintana** [comment]
I managed to make it more reproducible by adding multiple kafka inputs (which my is my use case):
```
input {
  kafka {
    topics => ["test_topic1"]
    bootstrap_servers => "localhost:9093,localhost:9095"
    group_id => "test_group1"
    codec => json
    type => "test_type"
#    security_protocol => "SSL"
    ssl_truststore_location => "localhost.trust.jks"
    ssl_truststore_password => "localhost"
  }
  kafka {
    topics => ["test_topic2"]
    bootstrap_servers => "localhost:9093,localhost:9095"
    group_id => "test_group2"
    codec => json
    type => "test_type"
#    security_protocol => "SSL"
    ssl_truststore_location => "localhost.trust.jks"
    ssl_truststore_password => "localhost"
  }
  kafka {
    topics => ["test_topic3"]
    bootstrap_servers => "localhost:9093,localhost:9095"
    group_id => "test_group3"
    codec => json
    type => "test_type"
#    security_protocol => "SSL"
    ssl_truststore_location => "localhost.trust.jks"
    ssl_truststore_password => "localhost"
  }
  kafka {
    topics => ["test_topic4"]
    bootstrap_servers => "localhost:9093,localhost:9095"
    group_id => "test_group4"
    codec => json
    type => "test_type"
#    security_protocol => "SSL"
    ssl_truststore_location => "localhost.trust.jks"
    ssl_truststore_password => "localhost"
  }
}
output {
  stdout {
    codec => rubydebug {}
  }
}
```

**Comment by gquintana** [comment]
It was a Kafka client issue, see https://issues.apache.org/jira/browse/KAFKA-4491 and https://issues.apache.org/jira/browse/KAFKA-4493 .
In short Kafka client takes a 4 bytes in the TCP stream as the size to initialize a byte buffer. As the TCP stream is SSL encrypted in contains any number https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/network/NetworkReceive.java#L78
