### ISSUE TITLE
Add log4j support to plugin versions < 3.0

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#154]
We added log4j support to plugin versions 3.0.1+.  For users using plugin versions < 3 for Kafka 0.8 clients, it is difficult to debug issues thrown by the underlying Kafka client because we swallowed the full error stack and often do not provide much debugging information at the --debug level.

**Comment by suyograo** [comment]
Fixed https://github.com/logstash-plugins/logstash-input-kafka/commit/09a9a0c4d4fe19c8f7e047016f73b1233782f0b0
