### ISSUE TITLE
Logstash Kafka Version compatibility

### ISSUE THREAD

**Issue by sherry-ger** [logstash-plugins/logstash-input-kafka#161]
* Version: 5.1.1
* Operating System: None
* Config File (if you have sensitive info, please remove it): None
* Sample Data: None
* Steps to Reproduce: None

The Kafka input and output plugins compatibility charts contain incorrect info as the Kafka plugins in LS 5.1 supports Kafka 0.9

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html

**Comment by dedemorton** [comment]
@sherry-ger Just an FYI that I've already updated the ruby source files that contain the doc source to include this info: https://github.com/logstash-plugins/logstash-output-kafka/pull/108/files and https://github.com/logstash-plugins/logstash-input-kafka/pull/156. These changes will be picked up when we regenerate the plugin docs for the next release. In the meantime, I do plan to tweak the generated doc to fix the problem (will do that sometime this week).

**Comment by biskandar** [comment]
I have used the Kafka 2.12 , and seems logstash-in/ouput-kafka doesn't not support yet ( only installed until version 5.x ) , do you know how to make it works ?

**Comment by dedemorton** [comment]
Closing because this issue is old (no longer valid for 6.x). We've streamlined the content about compatibility in the docs for the plugin.
