### ISSUE TITLE
Using more than 1 consumer thread produces incorrect JMX consumer metrics 

### ISSUE THREAD

**Issue by talvey** [logstash-plugins/logstash-input-kafka#165]
**Env Details:**
Logstash 2.4.0
logstash-input-kafka-6.2.0
Kafka 0.10.1
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Issue:**
Configuring more than 1 "consumer_threads" artificially decreases the "records-consumed-rate" JMX MBean attribute.  It appears the rate is divided by the number of threads, or only a single thread is reporting.  So, using 2 threads cuts the value in half, while using 3 threads will show 1/3 the actual rate.

To reproduce, you can do a simple config like this

```
input {
    kafka {
 ...
        consumer_threads => 2
 ...

    }
}
filter {
  metrics {
      meter => "events"
      flush_interval => 10
      add_tag => "metric"
  }

}
output {
    if "metric" in [tags] {
        stdout {
          codec => line {
            format => "1m rate: %{[events][rate_1m]} | 5m rate: %{[events][rate_5m]}"
          }
        }
     }
}

```
Then connect JConsole (or whatever JMX view you like) and compare the following jmx metric with the internally generated logstash metrics.
```
kafka.consumer
	logstash
		[your topic name]
			attributes
				records-consumed-rate
```

In this case you'll see the internally generated metric will be double the jms metric.  Note:  I have verified the actual message throughput (more or less) matches the internal metric.

**Comment by jordansissel** [comment]
I don't think we support (or test) JMX with Logstash. @suyograo or @talevy or @andrewvc may know more about this issue though.

**Comment by talevy** [comment]
right, I have not reviewed how Kafka decides to report. The truth is that there are multiple consumer instances being run on separate threads, not sure if you can discern the difference between these in jmx.

**Comment by talvey** [comment]
Ok, understood.  If it helps, in previous versions (2.0.9 I think) the JMX metrics were reported correctly.

**Comment by suyograo** [comment]
Handled by #166
