### ISSUE TITLE
Update to latest 0.8.2.1 Kafka

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-kafka#17]
Currently Kafka 0.8.2.0 RC1 is out -- we should test and upgrade to 0.8.2.0 when it is GA

https://mail-archives.apache.org/mod_mbox/kafka-dev/201501.mbox/%3CCAFc58G_-6N2HWRr4Ddu-TeX%3Dmx3QgJziZXfxzMbdTab6Tv3xzA%40mail.gmail.com%3E

Update: We are at version 0.8.2.1

**Comment by talevy** [comment]
@joekiller, have you thought about upgrading `jruby-kafka` to kafka-0.8.2?
I can help with that if it is not a priority for you at the moment!

**Comment by joekiller** [comment]
I have a little but was waiting for it to stabilize more.  I know they had
a few outstanding cpu consumption issues. See here
http://mail-archives.apache.org/mod_mbox/kafka-users/201502.mbox/%3CCAFc58G_Tsbh043q5Gj1hE61u8D-4Maj_hcfoLyVC5tnCvbHCdw@mail.gmail.com%3E

Feel free to kick it around though.  I'll work in the PRs after we test
some.

**Comment by talevy** [comment]
ah ok. I haven't been following up on that closely.

**Comment by joekiller** [comment]
on second pass I think it is ok to work on 0.8.2.0, it was 0.8.2.1 that was having problems

**Comment by joekiller** [comment]
Looks like 0.8.2.1is about ready anyway: https://people.apache.org/~junrao/kafka-0.8.2.1-candidate2/RELEASE_NOTES.html

**Comment by joekiller** [comment]
I got 0.8.2.1 in jruby-kafka 1.3.0.  It still uses the old producer but that is forthcoming.

**Comment by talevy** [comment]
thanks @joekiller, closing.
