### ISSUE TITLE
Changed config option names between LS v5 and v2 warrant breaking changes notes?

### ISSUE THREAD

**Issue by joshuar** [logstash-plugins/logstash-input-kafka#170]
It looks like several of the config options for this plugin changed names between Logstash v2 and v5.  For example, the following v2 config for this plugin:

```ruby
kafka {
    decorate_events => true
    topic_id => "foobar"
    zk_connect => "server1:12181,server2:12181,server3:12181"
    codec => "plain"
    group_id => "some_group"
    consumer_id => "logstash_host1 "
    type => "stuff" 
} 
```

Has become the following in v5:

```ruby
kafka {
  decorate_events => true
  topics => ["foobar"]
  bootstrap_servers => "server1:12181,server2:12181,server3:12181"
  codec => "plain"
  group_id => "some_group"
  client_id => "logstash_host1"
  type => "stuff"
}
```

i.e.:

* `topic_id` changed to `topics` and now is an array format
* `zk_connect` changed to `boostrap_servers`
* `consumer_id` changed to `client_id`

I feel this warrants mentioning in the [Breaking Changes](https://www.elastic.co/guide/en/logstash/current/breaking-changes.html) docs?

**Comment by acchen97** [comment]
@joshuar this is already in the breaking changes as far as I can see.

https://www.elastic.co/guide/en/logstash/current/breaking-changes.html#_plugin_versions

**Comment by joshuar** [comment]
@acchen97 indeed, I see that now.  But that I guess is the problem. Breaking changes for other plugins are explicitly called out in their own sections while the breaking changes for Kafka are used as an example in the Plugin Versions section.  I feel it should be in a separate section like the other plugins where it can't be easily missed as the last paragraph in a larger section?

**Comment by acchen97** [comment]
@suyograo @dedemorton thoughts on this one?

**Comment by suyograo** [comment]
I had thought we documented this in breaking changes, but I don't see it :/ Most of the configs changed from v2 to v5, so we should add a blanket "Kafka configs have changed. Please see the latest documentation" or something to that effect.

**Comment by suyograo** [comment]
I'm fixing this now.

**Comment by joshuar** [comment]
@suyograo yep we have, it just isn't very obvious.  I'm +1 on making this more obvious for popular plugins like Kafka.  Not sure we need to call out every change in every supported plugin, but highlighting the big changes in popular plugins easily would be more useful.

**Comment by suyograo** [comment]
@joshuar @dedemorton https://github.com/elastic/logstash/pull/6711

**Comment by dedemorton** [comment]
@suyograo Looks great. One question I have, though, is why we don't also list these changes in the relnotes. It seems like the relnotes should list all the changes, and the "Breaking Changes" topic should provide more detail on the changes that break stuff. I worry about users who might skim the relnotes without looking very closely at the breaking changes doc.

**Comment by suyograo** [comment]
Done. Merged. @dedemorton good point about release notes. We can do it moving forward.
