### ISSUE TITLE
4.x needs PR#103 from 5.x merged.

### ISSUE THREAD

**Issue by pbkdf3** [logstash-plugins/logstash-input-kafka#173]
Please merge this into 4.x.
https://github.com/logstash-plugins/logstash-input-kafka/pull/103

It works unchanged but may need work on the tests.  I am unable to currently sign the CLA or would do it and submit a new PR myself.

Lack of this leaves a critical feature missing for those who want  to run current logstash and require kafka .9.

**Comment by suyograo** [comment]
Merged in 6cae22b756004e0474d38719a85208e2a0cbd090

released as 4.2.0
