### ISSUE TITLE
Kafka 0.10.2.0

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#178]
This is created to track our upgrade to support Kafka 0.10.2.0 client.

**Comment by automotua** [comment]
May I know the status of the upgrade? Is there a timeline as in when the support for Kafka 0.10.2.0 will be out? Thanks!

**Comment by gquintana** [comment]
This feature looks very interesting because 0.10.2 client supports all 0.10 servers starting with 0.10.0:
https://issues.apache.org/jira/browse/KAFKA-4462
To me it would make maintaining Logstash Kafka plugin branches 5.x  (0.10.0) and 6.x (0.10.1) unnecessary.

**Comment by original-brownbear** [comment]
@suyograo in principle this should just work out of the box when upping the version to `0.10.2`, any reason not to put in that one-liner PR + bumped version and changelog here?

**Comment by jordansissel** [comment]
I like your proposal, Armin. Let's verify the claim that it really works
with all 3 versions (10.2, 10.1, 10.0) before we merge though.

**Comment by original-brownbear** [comment]
@jordansissel 

> . Let's verify 

As in manually try it out real quick or as in add an IT to run through those 3 versions (given we seem to have 0 tests involving an actual Kafka broker, this may not be the worst idea)?

**Comment by jordansissel** [comment]
Manually is ok for now. Long term I imagine we will add more complex
integration tests, but manual (one time) is good enough to satisfy my
distrust :)

**Comment by original-brownbear** [comment]
@jordansissel alright :) I actually tried this already by accident when looking into another issue. At least 10.1 works (I'll try the other combinations real quick too tomorrow). Two other problems come to mind:

* Ok not a problem, but `0.10.2.1` is out, I guess we'd rather go for that ? :)
* Actual problem: https://github.com/logstash-plugins/logstash-output-kafka/issues/127 => don't we have to upgrade both plugins at the same time and clearly document that you need to keep versions aligned when upgrading? Otherwise some user configurations may end up with a mix of Kafka versions in the class path?

**Comment by original-brownbear** [comment]
@jordansissel one way to fix the classpath issue (If we actually care) would be to build a separate jar with all the jar dependencies and shade the Kafka library there.
Already did that for https://github.com/logstash-plugins/logstash-filter-useragent

**Comment by suyograo** [comment]
@original-brownbear Lets bump to 0.10.2.1 directly.

> As in manually try it out real quick or as in add an IT to run through those 3 versions (given we seem to have 0 tests involving an actual Kafka broker, this may not be the worst idea)?

We do have integration tests with real Kafka brokers which runs on travis. See here: https://github.com/logstash-plugins/logstash-input-kafka/blob/master/kafka_test_setup.sh#L8

That needs to be changed as well. Anyhow this should work and integration tests should validate if so. +1 on moving forward with this on both input and output.

**Comment by suyograo** [comment]
> Otherwise some user configurations may end up with a mix of Kafka versions in the class path?

This is typically users understanding. They would upgrade both (input and output) or none.

**Comment by original-brownbear** [comment]
@suyograo here we go: https://github.com/logstash-plugins/logstash-input-kafka/issues/178 sec adding one for output as well

**Comment by suyograo** [comment]
Fixed in #189
