### ISSUE TITLE
decorate_events content conflicts with metricbeat's kafka mapping

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#180]
The decorate_event option in the kafka input adds pieces of information to the LS event like the following

```
  "kafka": {
    "consumer_group": "beats_indexers",
    "partition": 0,
```

However, this conflicts with [metricbeat's template](https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.template.json#L1732) where kafka.partition is an object, not a concrete value.

As a result, if you have something like metricbeats -> kafka -> LS (with decorate_events) -> ES (configured to use the metricbeats template), then all the events flowing through will fail with a mapping exception.

@talevy

**Comment by jordansissel** [comment]
No news to report at this time. If you are interested in this issue, please indicate so on this issue using github's reactions feature.

**Comment by jordansissel** [comment]
Fixing this would be a breaking change, therefore after any patches are merged, this will only become available at earliest in the next major release of Logstash

**Comment by acchen97** [comment]
@suyograo @tsg @ruflin there appears to be a mapping conflict for the `kafka.partitions` field between the [Metricbeat Kafka module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-kafka-partition.html) and the Logstash Kafka input.

The Logstash kafka input [decorate_event option](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-decorate_events) will enrich the event with metadata via a `kafka` object field, with subfields `topic`, `consumer_group`, `partition`, `offset`, and `key`. It appears the particular offender is the partition field, but I wonder if there are other conflicts of similar flavor.

Having Metricbeat metrics and Kafka metadata lumped into the same object seems confusing at best. Perhaps it may make sense to rename the `kafka` object field LS uses to `@kafka` or `kafka_metadata`. Thoughts?

**Comment by jordansissel** [comment]
Let's tentatively target this at the 7.0 time frame.

**Comment by suyograo** [comment]
Move this to `@metadata`
