### ISSUE TITLE
Allow using no group ID and starting at first / last offset

### ISSUE THREAD

**Issue by joewreschnig** [logstash-plugins/logstash-input-kafka#185]
Especially when testing new filters, I often just want to start streaming data from "now" without bothering with a saved position. But using `nil` or `null` in my logstash config gives me a group ID of literally "nil" and "null", and using an empty string throws `org.apache.kafka.common.errors.InvalidGroupIdException: The configured groupId is invalid`. Our Kafka configuration uses long-lived consumer offsets, and it's a little annoying to have to update my group ID to 'test2', 'test3', etc. each time I want to fast-forward it, and to see those in kafka group lists.

Is it possible to for the plugin to start only at the beginning / end (based on `auto_offset_reset`) and not save any group ID at all?

**Comment by original-brownbear** [comment]
@joewreschnig 
The only thing we could do here would be to assign a random consumer group if the field is left blank I think.

Maybe a solution to your issue would be to simply drop consumer group data using Kafka's

```
bin/kafka-consumer-groups.sh --reset-offset
```

command? :)

**Comment by joewreschnig** [comment]
That feature is only nine days old and we don't have a 0.11 upgrade scheduled yet.

Is that really the only thing possible? We have a number of consumer applications based on rdkafka, and they have no problem starting up a consumer without a persistent ID.

**Comment by original-brownbear** [comment]
@joewreschnig the problem is that we're not using the simple consumer approach in the plugin at the moment and are actually subscribing to topics and committing offsets back to Kafka.

>  I'm not very knowledgeable about Kafka internals, so maybe it jumps through a lot of hoops to do that, but none of that complexity ends up in the API.

It's not really jumping through a lot of hoops :) All it does is simply not write the offsets it consumed back to Kafka. Let me investigate how much effort it would be to offer a setting for this consumer strategy with our current APIs/implementation, will get back to you shortly!

**Comment by original-brownbear** [comment]
@joewreschnig ignore my previous comment I deleted it. We already have to option to turn off auto_commit implemented:

setting `enable_auto_commit` to `"false"` should give you exactly the behavior you desire. My bad for wasting time here!

**Comment by joewreschnig** [comment]
That's working, thanks!
