### ISSUE TITLE
Logging can't be initialized

### ISSUE THREAD

**Issue by fhopf** [logstash-plugins/logstash-input-kafka#187]
Log4j doesn't seem to be provided with the Kafka input. This would very likely help with diagnosing problems.

Startup (Logstash 5.2.2, Input-Kafka 5.1.6)
```
log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.consumer.ConsumerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by svrc-pivotal** [comment]
in the gemspec, replace

`  s.requirements << "jar 'org.slf4j:slf4j-log4j12', '1.7.21'"`

with 

`  s.requirements << "jar 'org.apache.logging.log4j:log4j-slf4j-impl', '2.8.2'"`

and rebuild the gem.   

Also the Kafka library itself doesn't seem to respect the root logger level, it's INFO by default, so if you want to debug, you'll want to include a section for kafka in your `log4j2.properties`, i.e.
```
logger.kafka.name=org.apache.kafka
logger.kafka.appenderRef.console.ref=console
logger.kafka.level=debug
```

I may file a PR for these this weekend, ran into them myself.

**Comment by guyboertje** [comment]
Merged PR. Closing. I'm waiting a short while for @consulthys to update his PR for new gem version.
