### ISSUE TITLE
NPE when using Kerberos + SSL

### ISSUE THREAD

**Issue by LionelCons** [logstash-plugins/logstash-input-kafka#190]
Running against Kafka 0.10.2.1 with Kerberos and `SASL_PLAINTEXT`, everything works fine.

When using `SASL_SSL`, with the same configuration (except the port numbers), I get the cryptic:
```
Unable to create Kafka consumer from given configuration {:kafka_error_message=>java.lang.NullPointerException, :cause=>nil}
```

**Comment by suyograo** [comment]
Fixed
