### ISSUE TITLE
topics_pattern not working with logstash 5.4.0 and kafka-input 5.1.7

### ISSUE THREAD

**Issue by harelmoshe** [logstash-plugins/logstash-input-kafka#202]
I've setup the following, simple pipeline:
```
input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics_pattern => "aaa.bbb_ccc.*"
  }
}

output {
  stdout { }
}
```
and logstash starts successfully with no issues written to the log in debug mode. 
However, it doesn't consume any message from the topic (new or pre-existing), while kafkacat started in parallel is consuming the events from the same broker and topic correctly.

Has anyone ever managed run a working example using `topics_pattern`? I'm trying to read from multiple topics fed through an environment variable, so it doesn't make sense to define an input-per-topic or use the `topics => ["aaa.bbb_ccc.1", aaa.bbb_ccc.2" ... "aaa.bbb_ccc.n"]` syntax instead.

Any ideas what might be missing or wrong with this usage pattern?

**Comment by GoodMirek** [comment]
Same issue happens to me. Have you ever managed to make it working?

**Comment by original-brownbear** [comment]
@harelmoshe @GoodMirek 

I just tried this out with the most recent version of this plugin `6.3.2` and it works for me as long as I start Logstash with the topics already existing in Kafka.

For creating topics and having them be subscribed to right away you will need to lower the setting for `metadata_max_age_ms`, the default here is `300000` == 5 minutes. After those 5 minutes, the new topic should be subscribed to just fine as well in the default configuration.

**Comment by GoodMirek** [comment]
@original-brownbear Thanks, it works now for me.

**Comment by original-brownbear** [comment]
@GoodMirek alright good news then :) Closing

**Comment by nicknameforever** [comment]
@original-brownbear What is the status of this issue? Is there any 5.4.x Logstash release where the option `topics_pattern` works?

**Comment by original-brownbear** [comment]
@nicknameforever is it broken for you even with a lower value for `topics_pattern`, i.e. does the subscription metadata never refresh correctly?

**Comment by nicknameforever** [comment]
@original-brownbear I am using the version `5.4.0` (it has the plugin `5.1.6`) and the input does not read anything. If I try to set the option `metadata_max_age_ms` then I get: 
```
[ERROR][logstash.inputs.kafka    ] Unable to create Kafka consumer from given configuration {:kafka_error_message=>#<NameError: uninitialized constant Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::METADATA_MAX_AGE_MS_CONFIG>, :cause=>nil}
```

**Comment by original-brownbear** [comment]
@nicknameforever what did you put as the value for `metadata_max_age_ms` in your config?

**Comment by nicknameforever** [comment]
@original-brownbear for example:
```
metadata_max_age_ms => 1000
```
But the error is the same if it is a string with integer and with any other integer value.

**Comment by original-brownbear** [comment]
@nicknameforever sorry yea that won't help, this is an outright bug in the syntax (undefined constant, seems to be some version conflict) it seems.

One question, are you also running Kafka output (or anything else that may bring the Kafka client library into your classpath)?

**Comment by nicknameforever** [comment]
@original-brownbear No kafka output in the pipeline. If it helps the kafka broker version is `0.10.2.1`.

**Comment by original-brownbear** [comment]
@nicknameforever ok, then this is a bug in that version most likely (your broker won't leak anything into your class path). I think the easiest option for you to get around this would be upgrading to `6.3.4` which is backward compatible with your broker and LS version.

**Comment by GoodMirek** [comment]
I confirm that I am running kafka input plugin for logstash version `6.3.4` and `topics_pattern` works for me.

**Comment by nicknameforever** [comment]
@GoodMirek What is your kafka broker version?

**Comment by GoodMirek** [comment]
I run three environments:
1. One node cluster kafka_2.11-0.10.2.0, logstash-input-kafka (6.3.0), logstash 2.4.0
2. Two node cluster kafka_2.11-0.11.0.0, logstash-input-kafka (6.3.0), logstash 2.4.0
3. Two node cluster kafka_2.11-0.11.0.0, logstash-input-kafka (6.3.3), logstash 2.4.0

All are running on Ubuntu 16.04.2 LTS, zookeeper 3.4.8. In all envs I use `topics_pattern`.

**Comment by nicknameforever** [comment]
@original-brownbear The option `topics_pattern` works for me after all (logstash 5.4.0). It was a misconfigured topic pattern. 
But if I specify  `metadata_max_age_ms` it still breaks the input.

**Comment by original-brownbear** [comment]
@nicknameforever happy to hear the `topics_pattern` issue is fixed. I'm afraid my hands are tied regarding the `metadata_max_age_ms` setting issue and only an update of the plugin version will fix this, sorry.
