### ISSUE TITLE
Upgrade to Kafka 0.11

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-input-kafka#205]
Kafka `0.11` is out and backward compatible with `0.10.x` => we should upgrade the library we use here.

**Comment by allenmchan** [comment]
Hi @original-brownbear, will there be equivalent task for kafka output?

**Comment by original-brownbear** [comment]
@allenmchan now there is (https://github.com/logstash-plugins/logstash-output-kafka/issues/139), thanks for pointing that out!

**Comment by original-brownbear** [comment]
done
