### ISSUE TITLE
Logstash-input-kafka does not build properly

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-input-kafka#21]
Hi,
  if you bundle to have all the dependencies installed from a fresh repo, you get actually the next error:

```
Installing sinatra 1.4.5
Installing stud 0.0.19
Installing polyglot 0.3.5
Installing treetop 1.4.15
Using logstash 1.5.0.beta1 from git://github.com/elasticsearch/logstash.git (at 1.5)
Installing logstash-codec-json 0.1.5
Installing logstash-codec-plain 0.1.4
[ERROR] Failed to execute goal on project logstash-input-kafka: Could not resolve dependencies for project rubygems:logstash-input-kafka:gem:0.1.8: Failed to collect dependencies at rubygems:logstash:gem:[1.4.0,2.0.0): No versions available for rubygems:logstash:gem:[1.4.0,2.0.0) within specified range -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

it looks like there is an issue with the dependency management, might be the jar-dependencies as it got a new minor version (that might have broken something here).

more details (this is using an old Gemfile.lock for this repo):

```
Resolving dependencies...
Bundler could not find compatible versions for gem "jar-dependencies":
  In snapshot (Gemfile.lock):
    jar-dependencies (0.1.2)

  In Gemfile:
    logstash (>= 0) java depends on
      jar-dependencies (= 0.1.7) java
```

**Comment by ph** [comment]
![wat](https://cloud.githubusercontent.com/assets/640/6154495/28316cb6-b1fa-11e4-802f-3ddf2b38cf1c.jpg)

**Comment by ph** [comment]
All the jar gems are touched by this, ruby-maven and jar-dependencies were upgraded on February 9

**Comment by joekiller** [comment]
If it makes you feel any better, logstash-output-elasticsearch has the same problem: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/53

**Comment by ph** [comment]
@joekiller thx,

@purbon if you freeze the version of the previous `ruby-maven` it will work.

```ruby
gem "ruby-maven", "3.1.1.0.8"
```

I am looking at what changed between the releases.

**Comment by ph** [comment]
@purbon I'll push an update tomorrow to the devutils that should fix the issues and makes jenkins, I am still trying to nail it to do a bug report upstream.

**Comment by jsvd** [comment]
they're quite different:

```
% ls ruby-maven-3.1.1.0.*/lib
ruby-maven-3.1.1.0.8/lib:
tesla-polyglot-cli-0.1.1.jar     tesla-polyglot-common-0.1.1.jar

ruby-maven-3.1.1.0.9/lib:
maven/          ruby-maven.rb   ruby_maven.rb   tesla_maven.rb
```

**Comment by purbon** [comment]
@ph thanks for the debugging, I think going to freeze the jar-dependency/ruby-maven version is a good way to go. 

For other situation, we should be sure to freeze important libraries like this to a "working version", so we face upgrade errors like this in a controlled way.

**Comment by purbon** [comment]
Should be fix https://github.com/logstash-plugins/logstash-input-kafka/pull/22

**Comment by suyograo** [comment]
Fixed via https://github.com/logstash-plugins/logstash-input-kafka/pull/22
