### ISSUE TITLE
`metadata_max_age_ms` setting is broken

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-input-kafka#218]
Setting that setting causes:

```sh
[logstash.inputs.kafka    ] Unable to create Kafka consumer from given configuration {:kafka_error_message=>#<NameError: uninitialized constant Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::METADATA_MAX_AGE_MS_CONFIG>, :cause=>nil}
[2017-08-03T17:31:25,741][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
```

also seen here https://github.com/logstash-plugins/logstash-input-kafka/issues/202#issuecomment-317729812 for users.

It seems the constant name in the Kafka library changed. The has been reported widely, but I couldn't reproduce it outright locally, could be we're having some trouble with the build caching the library jar in some messed up way here.

**Comment by original-brownbear** [comment]
fixed in #220

**Comment by shreyu86** [comment]
@original-brownbear Thanks a lot for fixing this, what would be the ETA for this to make it's way to the release?

**Comment by original-brownbear** [comment]
@shreyu86 this is already fixed in releases `8.0.1+`

**Comment by original-brownbear** [comment]
my bad for failing to close the issue back then :(

**Comment by shreyu86** [comment]
I am using the logstash docker image `docker.elastic.co/logstash/logstash:5.6.0` and when I list the plugins I see `logstash-input-kafka (5.1.11)` am I missing something?

**Comment by shreyu86** [comment]
False alarm, I had connectivity issues, was able to upgrade to 8.0.2

**Comment by original-brownbear** [comment]
@shreyu86 happy to hear that :)
