### ISSUE TITLE
Logstash can not read data from kafka 

### ISSUE THREAD

**Issue by xiaoxinba** [logstash-plugins/logstash-input-kafka#227]
logstash can not read data from kafka ;from kafka, roup_id's offset about one topic can not change;
why???

**Comment by suyograo** [comment]
@xiaoxinba can you add more details? this report is not enough for us to help debug. 
Also, please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!

**Comment by xiaoxinba** [comment]
@suyograo   Yes i know , the more detail see: https://discuss.elastic.co/t/logstash-kafka-input-plugin-can-not-read-data-from-kafka/98164;

thank you !!!
