### ISSUE TITLE
Unable to read from kafka input plugin 5.1.11

### ISSUE THREAD

**Issue by xueyejus** [logstash-plugins/logstash-input-kafka#234]
I can read message by kafka-consumer but kafka input plugin in logstash. And logstash log shows that Kafka version is 0.10.0.1.
**Logstash config:**
`input {
	kafka{
		bootstrap_servers => "192.168.0.162:9092"
		topics => "logstash"
		group_id => "logstash" 
	  }
  }
output {
  stdout {}
}`
**Version:**
logstash-input-kafka-5.1.11
kafka_2.12-0.11.0.1
logstash 5.6.3

**Logstash log:**
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.178590433Z Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.221734187Z 06:29:25.216 [main] INFO  logstash.modules.scaffold - Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.222563986Z 06:29:25.222 [main] INFO  logstash.modules.scaffold - Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.485128726Z 06:29:25.484 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.499237480Z 06:29:25.499 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.587153905Z 06:29:25.585 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618402667Z 06:29:25.617 [[main]<kafka] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618427800Z 	metric.reporters = []
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618431957Z 	metadata.max.age.ms = 300000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618434853Z 	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618438162Z 	reconnect.backoff.ms = 50
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618441019Z 	sasl.kerberos.ticket.renew.window.factor = 0.8
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618443965Z 	max.partition.fetch.bytes = 1048576
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618446713Z 	bootstrap.servers = [192.168.0.162:9092]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618449348Z 	ssl.keystore.type = JKS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618452149Z 	enable.auto.commit = false
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618455021Z 	sasl.mechanism = GSSAPI
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618457706Z 	interceptor.classes = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618460317Z 	exclude.internal.topics = true
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618463214Z 	ssl.truststore.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618465760Z 	client.id = logstash-0
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618468478Z 	ssl.endpoint.identification.algorithm = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618471232Z 	max.poll.records = 2147483647
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618473891Z 	check.crcs = true
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618476408Z 	request.timeout.ms = 40000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618479491Z 	heartbeat.interval.ms = 3000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618482480Z 	auto.commit.interval.ms = 5000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618485096Z 	receive.buffer.bytes = 65536
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618487893Z 	ssl.truststore.type = JKS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618490593Z 	ssl.truststore.location = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618493132Z 	ssl.keystore.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618495826Z 	fetch.min.bytes = 1
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618498416Z 	send.buffer.bytes = 131072
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618501097Z 	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618503827Z 	group.id = logstash
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618517827Z 	retry.backoff.ms = 100
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618520855Z 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618523618Z 	sasl.kerberos.service.name = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618526250Z 	sasl.kerberos.ticket.renew.jitter = 0.05
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618529013Z 	ssl.trustmanager.algorithm = PKIX
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618531597Z 	ssl.key.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618534347Z 	fetch.max.wait.ms = 500
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618537093Z 	sasl.kerberos.min.time.before.relogin = 60000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618539819Z 	connections.max.idle.ms = 540000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618542627Z 	session.timeout.ms = 30000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618545148Z 	metrics.num.samples = 2
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618547850Z 	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618550692Z 	ssl.protocol = TLS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618553211Z 	ssl.provider = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618555834Z 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618558457Z 	ssl.keystore.location = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618561137Z 	ssl.cipher.suites = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618563786Z 	security.protocol = PLAINTEXT
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618566428Z 	ssl.keymanager.algorithm = SunX509
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618569197Z 	metrics.sample.window.ms = 30000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618571797Z 	auto.offset.reset = latest
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.618574384Z 
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652536785Z 06:29:25.652 [[main]<kafka] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652555967Z 	metric.reporters = []
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652559497Z 	metadata.max.age.ms = 300000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652562412Z 	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652565429Z 	reconnect.backoff.ms = 50
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652568173Z 	sasl.kerberos.ticket.renew.window.factor = 0.8
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652570912Z 	max.partition.fetch.bytes = 1048576
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652573627Z 	bootstrap.servers = [192.168.0.162:9092]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652576417Z 	ssl.keystore.type = JKS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652578991Z 	enable.auto.commit = false
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652581916Z 	sasl.mechanism = GSSAPI
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652584476Z 	interceptor.classes = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652587197Z 	exclude.internal.topics = true
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652589919Z 	ssl.truststore.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652592485Z 	client.id = logstash-0
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652595161Z 	ssl.endpoint.identification.algorithm = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652606676Z 	max.poll.records = 2147483647
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652609988Z 	check.crcs = true
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652612712Z 	request.timeout.ms = 40000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652615262Z 	heartbeat.interval.ms = 3000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652617889Z 	auto.commit.interval.ms = 5000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652620739Z 	receive.buffer.bytes = 65536
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652623371Z 	ssl.truststore.type = JKS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652626142Z 	ssl.truststore.location = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652628871Z 	ssl.keystore.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652631400Z 	fetch.min.bytes = 1
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652634253Z 	send.buffer.bytes = 131072
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652636848Z 	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652639732Z 	group.id = logstash
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652642243Z 	retry.backoff.ms = 100
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652644956Z 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652647665Z 	sasl.kerberos.service.name = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652650367Z 	sasl.kerberos.ticket.renew.jitter = 0.05
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652652981Z 	ssl.trustmanager.algorithm = PKIX
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652655618Z 	ssl.key.password = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652658169Z 	fetch.max.wait.ms = 500
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652660713Z 	sasl.kerberos.min.time.before.relogin = 60000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652663457Z 	connections.max.idle.ms = 540000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652666026Z 	session.timeout.ms = 30000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652668611Z 	metrics.num.samples = 2
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652671243Z 	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652674024Z 	ssl.protocol = TLS
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652676545Z 	ssl.provider = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652679176Z 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652681864Z 	ssl.keystore.location = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652686229Z 	ssl.cipher.suites = null
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652688877Z 	security.protocol = PLAINTEXT
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652691653Z 	ssl.keymanager.algorithm = SunX509
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652694412Z 	metrics.sample.window.ms = 30000
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652697056Z 	auto.offset.reset = latest
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.652699906Z 
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.678425887Z 06:29:25.678 [[main]<kafka] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.10.0.1
logstash-ptstatistics_logstash-ptstatistics_1 | 2017-10-30T06:29:25.678449227Z 06:29:25.678 [[main]<kafka] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : a7a17cdec9eaa6c5

**Comment by jordansissel** [comment]
There's not enough information here to make a guess -- at minimum, showing your working kafka consumer would help. Are you certain Logstash is configured correctly? Is Kafka reachable and working? Is the topic name 'logstash' correct? Is there new data being produced into this topic *after* Logstash starts? (your offset is 'latest' so it may ignore any existing data)

**Comment by xueyejus** [comment]
@jordansissel Thanks for reply. I changed kafka with kafka_2.11-0.10.0.1. It works...

Kafka Client Version | Logstash Version | Plugin Version | Why?
0.8 | 2.0.0 - 2.x.x | <3.0.0 | Legacy, 0.8 is still popular
0.9 | 2.0.0 - 2.3.x | 3.x.x | Works with the old Ruby Event API (event['product']['price'] = 10)
0.9 | 2.4.x - 5.x.x | 4.x.x | Works with the new getter/setter APIs (event.set('[product][price]', 10))
0.10.0.x | 2.4.x - 5.x.x | 5.x.x | Not compatible with the ⇐ 0.9 broker

Is logstash-input-kafka-5.1.11 not compatible with kafka_2.12-0.11.0.1?
