### ISSUE TITLE
Add support for Confluent's Avro Serializers / Deserializers

### ISSUE THREAD

**Issue by dkelley-accretive** [logstash-plugins/logstash-input-kafka#238]
We have a use case where we want to read avro encoded kafka events into logstash using the Confluent KafkaAvroDeserializer https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java which handles fetching the avro schema from the Confluent schema registry and using it to deserialize the event into a gereric avro record.  I have a working patch that adds this functionality but I'm not sure if you are interested in adding it into the plugin or not due to it depending on part of the Confluent platform when it currently only has dependencies from Apache Kafka.

**Comment by andrewvc** [comment]
@original-brownbear what would be involved in adding this to the kafka input?

/CC @jsvd

**Comment by jsvd** [comment]
in the same fashion of the jdbc input, we could support an optional path based option that would point to a .jar file containing, for example, the compiled KafkaAvroDeserializer

**Comment by bquinart** [comment]
How does this relate to #37 ?
We also need to ingest Confluent style Avro messages from Kafka.
It sounds like both issues address this, however the proposed solutions seem to differ.

**Comment by dkelley-accretive** [comment]
@bquinart This looks like the same issue, but as you noted different solutions.  Here I am adding the ability to use the KafkaAvroDeserializer directly.  The other solution has a custom codec that knows how to interact with the schema registry.  I haven't tested their solution, but I assume it also works fine.

**Comment by ojairob** [comment]
Any traction on this?  Work arounds?

**Comment by original-brownbear** [comment]
@jsvd passing this to you. In theory your proposal should work here I think though :)

**Comment by dineshspn** [comment]
I have a similar need to read a Avro from kafka (confluent) deserialize and push it to elasticsearch using logstash. Can you add a little details on how you guys achieved it. It would be really helpful. 

Thanks!

**Comment by ojairob** [comment]
I was not able to figure it out

**Comment by roaksoax** [comment]
We believe this issue has now been solved in version 10.6.0 of the Kafka input from logstash-integration-kafka plugin.

This version allows defining the URL for the Confluent Schema Registry used to manage the Avro schemas (it also offers proxy settings to access this scheme specifically). More technical information can be found in the meta issue [1], or you can view the documentation in the plugin docs 

[1]: https://github.com/logstash-plugins/logstash-integration-kafka/issues/58
[2]: https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v10.6.0-plugins-inputs-kafka.html#v10.6.0-plugins-inputs-kafka-schema_registry_url

If this request has not been addressed in the above plugin, please create a new issue.
