### ISSUE TITLE
problems trying bin/plugin logstash-input-kafka .. suggests logstash-core dependency, which doesn't exist

### ISSUE THREAD

**Issue by Analect** [logstash-plugins/logstash-input-kafka#27]
I was trying to get logstash1.5 working in docker, using https://github.com/roblayton/docker-logstash as a template and editing the run.sh in that repo just to run logstash on creation of the container and using a -v flag in docker to point to the logstash.conf (see lower down) on my host, as well as linking into various other containers (zookeeper and elasticsearch).

docker run -v /home/me/Development/Tools/data/logstash/config/:/etc/logstash/conf.d/ -d -p 5043:5043 -p 9292:9292 --name logstash1.5 --link elasticsearch:es --link zookeeper:zk -t roblayton/docker-logstash

This gives the following error:
Using milestone 1 input plugin 'kafka'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
Failed to install template: Connection refused {:level=>:error}
kafka client threw exception, restarting {:exception=>#<KafkaError: Got ZkException: Unable to connect to zookeeper server within timeout: 6000>, :level=>:warn}
kafka client threw exception, restarting {:exception=>#<KafkaError: Got ZkException: Unable to connect to zookeeper server within timeout: 6000>, :level=>:warn}

I then thought that maybe the logstash1.5 beta was missing the logstash-input-kafka plugin and from within the logstash container I attempted to install that plugin.  I realised as part of that process that an earlier version of the plugin was in fact installed (0.1.5), but the install failed to install the newer version because of some unresolved dependencies on a logstash-core plugin, which doesn't appear to exist yet.  Any suggestions on a possible fix for this?

root@f6f3610dc8d5:/opt/logstash# bin/plugin install logstash-input-kafka
validating logstash-input-kafka >= 0
Valid logstash plugin. Continuing...
removing existing plugin before installation
Successfully uninstalled logstash-input-kafka-0.1.5
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: logstash-input-kafka (= 0.1.11) requires logstash-core (< 2.0.0, >= 1.4.0)
           resolve_for at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:144
           resolve_for at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:194
               resolve at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:87
               resolve at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/request_set.rb:134
  resolve_dependencies at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:408
               install at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:345
               execute at /opt/logstash/lib/logstash/pluginmanager/install.rb:60
                   run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/command.rb:67
               execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11
                   run at /opt/logstash/lib/logstash/runner.rb:144
                  call at org/jruby/RubyProc.java:271
                   run at /opt/logstash/lib/logstash/runner.rb:171
                  call at org/jruby/RubyProc.java:271
            initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/task.rb:12
root@f6f3610dc8d5:/opt/logstash# bin/plugin install logstash-core
validating logstash-core >= 0
Plugin does not exist 'logstash-core'. Aborting

This is the logstash.conf file that works on logstash 1.4 against kafka 0.8.1.1
input {
    kafka {
        zk_connect => "127.0.0.1:2181"
        group_id => "logstash"
	topic_id => "request"
        reset_beginning => false
        consumer_threads => 1
        queue_size => 20
        rebalance_max_retries => 4
	rebalance_backoff_ms => 2000
	consumer_timeout_ms => -1
	consumer_restart_on_error => true
	consumer_restart_sleep_ms => 0
	codec => json
        }
}
input {
    kafka {
        zk_connect => "127.0.0.1:2181"
        group_id => "logstash"
	topic_id => "response"
        reset_beginning => false
        consumer_threads => 1
        queue_size => 20
        rebalance_max_retries => 4
	rebalance_backoff_ms => 2000
	consumer_timeout_ms => -1
	consumer_restart_on_error => true
	consumer_restart_sleep_ms => 0
	codec => json
        }
}

filter {
	if [response][compressed] {
	  ruby {
	  	code => "
			require 'zlib';
			temp_payload = event['response']['payload']
			#buf_payload = new_payload.pack('C*') if new_payload.is_a?(Array)
			#puts compressYN
			#puts new_payload.class
			event['response']['payload_decoded']= Zlib::Inflate.inflate(temp_payload.to_a.pack('C*'))
		"
		}
   	 }
}

output {
#   stdout { codec => rubydebug }
	elasticsearch {
		protocol => "http"
		host => "localhost"
		index => "logs"
}
}

Thanks,
Colum

**Comment by suyograo** [comment]
@Analect Can you try with 1.5 RC2? we fixed a bunch of issues

**Comment by Analect** [comment]
Yes @suyograo 
That appears to work now.
Thanks.
