### ISSUE TITLE
 DNS resolution failed

### ISSUE THREAD

**Issue by CrazyBeeline** [logstash-plugins/logstash-input-kafka#274]
![image](https://user-images.githubusercontent.com/25030234/40221509-43724c32-5aaf-11e8-89d4-dd2e670ccf4f.png)

![image](https://user-images.githubusercontent.com/25030234/40221536-515393e2-5aaf-11e8-9289-504d454d790e.png)

![image](https://user-images.githubusercontent.com/25030234/40221544-56bfd96c-5aaf-11e8-9b94-79709cb68b52.png)

For all general issues, please provide the following details for fast resolution:

- Version:5.6.8
- Operating System: ubuntu_14.04
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by CrazyBeeline** [comment]
![image](https://user-images.githubusercontent.com/25030234/40221700-bd4a68b4-5aaf-11e8-80ab-868efb217dd4.png)

when I set like it works

**Comment by jsvd** [comment]
so it works with `kafka.*` but not `logbk.*`? I can't see how this plugin would be causing this, we simply use the kafka libraries for connecting to the broker.

**Comment by CrazyBeeline** [comment]
I'm sorry @jsvd my colleagues configured local DNS

I can't get the configuration in  etc/hosts  
when I run logstash  in docker
