### ISSUE TITLE
Add option to define custom deserializer class in input

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-kafka#28]
We should add an option to directly load a custom deserializer class in the input (the deserializer should be in the classpath). You can use Logstash codec to workaround this (see logstash-codec-avro for example), but it would be more convenient to expose this functionality directly to the end user. 

`config :deserializer_class, :validate => :string, :default => 'kafka.serializer.StringEncoder'`

**Comment by talevy** [comment]
the way about this for input is to use a Decoder. the only decoder provided within Kafka 0.8 is the `kafka.serializer.StringDecoder`. we will need to config options. one for the decoder class, and one for the jar that contains it so it can be added to logstash's classpath

**Comment by talevy** [comment]
PR for feature: https://github.com/logstash-plugins/logstash-input-kafka/pull/29

**Comment by suyograo** [comment]
Testing
