### ISSUE TITLE
Kafka 2.0 support

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#289]
Kafka 2.0 has been released.  This is to track the support of (and/or testing efforts around) the new major version for the input plugin.

**Comment by jsvd** [comment]
fixed in https://github.com/logstash-plugins/logstash-input-kafka/pull/290 and shipped in version 8.2.0 https://github.com/logstash-plugins/logstash-input-kafka/blob/master/CHANGELOG.md#820
