### ISSUE TITLE
Support `ssl.endpoint.identification.algorithm` property

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-input-kafka#298]
TLS endpoint verification checks are enabled/disabled in Kafka via the `ssl.endpoint.identification.algorithm` property. 

The default for this value was changed from '' to `https` for Kafka 2.0, turning on TLS endpoint verification by default, potentially breaking existing installations that did not require endpoint verification.

**Comment by inqueue** [comment]
Is there any way this can make 6.5.3?

**Comment by JackDavidson** [comment]
I've submitted a matching pull request to logstash-output-kafka:

https://github.com/logstash-plugins/logstash-output-kafka/pull/212

**Comment by inqueue** [comment]
Can this make 6.5.5?

**Comment by ceeeekay** [comment]
Just pointing out that until this is resolved we're stuck on 6.4.3, as upgrading either Kafka or Logstash will break our pipeline.

**Comment by robbavey** [comment]
This was fixed in #302 and released in version `8.3.1` of the plugin
