### ISSUE TITLE
tag corruption with RC2

### ISSUE THREAD

**Issue by ScottChapman** [logstash-plugins/logstash-input-kafka#31]
I am noticing tag corruption when using the current kafka input with logstash 1.5RC2. Here is a very simple config:
input {
    kafka {
        zk_connect => "localhost:3011"
        topic_id => "my_topic"
        type => "access"
    }
}
filter {
        mutate {
                add_tag => "whatever"
        }
}
output {
        stdout {
                codec => rubydebug
        }
}

This is what I get processing a simple message:
{
       "message" => "testing 1 2 3",
          "tags" => "_jsonparsefailurewhatever",
      "@version" => "1",
    "@timestamp" => "2015-04-16T22:10:07.726Z",
          "type" => "access"
}

If I change the kafka input to stdin I get what you would expect:
{
       "message" => "testing 1 2 3",
      "@version" => "1",
    "@timestamp" => "2015-04-16T22:09:34.144Z",
          "host" => "devfp03",
          "tags" => [
        [0] "whatever"
    ]
}

Possibly related we experience frequent logstash hangs when we are getting input from kafka topics.

**Comment by talevy** [comment]
The default `codec` in the kafka input plugin is `json`. To correct this `_jsonparsefailurewhatever` exception you can try setting this as your kafka input config

```
kafka {
zk_connect => "localhost:3011"
topic_id => "my_topic"
type => "access"
codec => plain
}
```

where the `codec => plain` option has been declared.

**Comment by wiibaa** [comment]
@talevy this seems related to https://github.com/logstash-plugins/logstash-codec-json/pull/6

**Comment by ScottChapman** [comment]
@talevy - Confirmed that adding codec => plain appears to have fixed it. Seems like it should just work properly with defaults.

Thanks this gives me a work-around for now.

**Comment by suyograo** [comment]
thanks @wiibaa. definitely related to logstash-plugins/logstash-codec-json#6
