### ISSUE TITLE
logstash6.6 with Kafka Client Version 0.8 input

### ISSUE THREAD

**Issue by rp-happiestbaby** [logstash-plugins/logstash-input-kafka#312]
Hi,
Im having problem with logstash-6.6 to connect to Kafka Client Version 0.8
There is no flag to set Kafka Client Version.
How do i do this ?

- Version: 6.6
- Operating System: ubuntu16.04

**Comment by jsvd** [comment]
hi @rp-happiestbaby, when you say kafka client version 0.8 do you mean the kafka broker is version 0.8?

Current versions of the kafka input plugin ship with kafka client version 2.1, and they can't connect to such an older version of the broker. The oldest version of kafka brokers we can connect to is 0.9, and you can install the kafka input plugin for that version with `bin/logstash-plugin install --version "4.0.0" logstash-input-kafka`

**Comment by lbx6z** [comment]
I can't connect to Kafka broker 0.9.0 with logstash 6.2.3 and logstash-input-kafka 8.0.4, but success with logstash 5.1.2 and logstash-input-kafka 4.2.0

https://github.com/logstash-plugins/logstash-input-kafka/issues/234#issuecomment-341046747

in this comment, he said only Plugin Version <= 4.x.x can work with 0.9.
Do you have any evidence?

**Comment by rp-happiestbaby** [comment]
hi @jsvd ,
yes kafka broker is version 0.8,
I need to install elasticsearch 6.6 and use logstash to consume from kafka broker version 0.8 and write to elasticsearch. What version plugin or/and logstash can i use ?

Thanks in advance 
Thanks for response
