### ISSUE TITLE
logstash-6.3.2 can not connect kafka 0.10.2,Please help

### ISSUE THREAD

**Issue by xzg121** [logstash-plugins/logstash-input-kafka#319]
Version:logstash-6.3.2,kafka0.10.2.1
Operating System:CentOS7.4
Config File :
input {
kafka {
bootstrap_servers => ["xxx:9092","xxx:9092,"xxx:9092"]
topics => ["xxx"]
group_id => "xxx"
}
}

**Comment by xzg121** [comment]
Version:logstash-6.3.2,kafka0.10.2.1
Operating System:CentOS7.4
Config File :
input {
        kafka {
                bootstrap_servers => ["xxx:9092","xxx:9092,"xxx:9092"]
                topics => ["xxx"]
                group_id => "xxx"
        }
}

**Comment by yaauie** [comment]
We use the Issues on github to track known issues with clear reproduction steps, and the [Logstash Forums](https://discuss.elastic.co/c/elastic-stack/logstash) for more conversation-based debugging. If this is still an issue, please open a new thread on the forum, and include relevant log messages.

**Comment by xzg121** [comment]
ok,thank you
