### ISSUE TITLE
Consumer group not reading from all partitions?

### ISSUE THREAD

**Issue by mheese** [logstash-plugins/logstash-input-kafka#32]
Hi there,

I have a setup with a kafka topic that has 6 partitions and 2 different logstash servers forming a consumer group of that topic and basically just outputting it to ElasticSearch. I configured the input currently with 3 workers on each server and a unique consumer group name.

The setup works fine for a few days. After that, however, it apparently is not consuming from all partitions anymore. I can see gaps in ElasticSearch that are pretty consistent with missing messages from certain partitions. I'm not a 100% sure if that is the issue, however, as the producer to this topic is not producing with a round-robin partitioner (see https://github.com/logstash-plugins/logstash-output-kafka/issues/17), it is hard to tell.

Please let me know what information you need for debugging this issue. I can provide complete logstash configs if that would be helpful.

**Comment by talevy** [comment]
Just to be clear:

you have 2 logstash agents running on separate machines. each is running 3 kafka inputs, where each input has a unique consumer group, different from the other two inputs?

To split a topic's messages across each of the workers/logstash instances, it is ideal that all belong to the same consumer-group.

The kafka input plugin leverages the official high-level consumer in Kafka, so it is already threaded for you. Not sure you need to go ahead and launch multiple input plugins on each logstash instance.

Am I understanding the topology / does that make sense?

**Comment by mheese** [comment]
No, that is not the case. I guess I need to paste my config before it becomes clear :) I'm not at a computer right now where I have access to it, will paste it later today.

I have 2 servers running logstash with *one* kafka-input (that input having 3 workers) belonging to the *same* consumer group.

**Comment by talevy** [comment]
by 3 workers, you mean you ran logstash with `-w 3` set?

**Comment by mheese** [comment]
consumer threads, as outlined here: http://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-consumer_threads

If I understand the documentation correctly, I should have 6 consumer threads in total if I have 6 partitions, and that makes 3 per server.

**Comment by talevy** [comment]
oh, that is what you mean by "workers". ok ok, sounds good. thanks for clarifying

**Comment by mheese** [comment]
is anybody looking into this? 

This basically means that the kafka input plugin is not usable unfortunately as it cannot be trusted (which is exactly the opposite that you want to reach by using it ...) :disappointed:

**Comment by joekiller** [comment]
Can you post your input configuration?  Also while your systems are running
can you tell us what the consumer offset checker is reporting?

https://cwiki.apache.org/confluence/display/KAFKA/System+Tools#SystemTools-ConsumerOffsetChecker

**Comment by joekiller** [comment]
Also check out this FAQ: https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Consumers

**Comment by mheese** [comment]
This is what my input section for Kafka looks like (not exactly, needed to scramble some values). There are 2 logstash servers running the same input definition with the same group ID. The topic has 6 partitions.

```
  kafka {
    consumer_restart_on_error => true
    consumer_restart_sleep_ms => 2000
    decorate_events => true
    group_id => "mygroup"
    topic_id => "mytopic"
    zk_connect => "server1:2181,server2:2181,server3:2181"
    type => "special_log"
    codec => plain {
      charset => "Windows-1252"
    }
    consumer_threads => 3
  }
```

Also, there are actually 2 other things I need to note (and probably create separate bug reports?):

1. Using more than one kafka input section does not work, one of the other definitions is not really used (haven't figured out a complete pattern here) / will never actually read input. I want to use that because I heavily make use of the "type" setting inside of an input for further distinction in filter sections. That way I would like to read from different topics and assign a different type to it.

2. The data in that input example here is actually in JSON format. However, if I use the "json" codec, it is basically telling me that the "nil" input is not in JSON format. If I use a JSON filter directly after the input, it works without complaints. 

Will get input on that consumer offset checker later, it is hard for me to transport any information out of that environment where things are running.

**Comment by joekiller** [comment]
I'd be curious to see what your consumer offsets are.  I'm guessing that some of the partitions are fully read while others are backed up.  Depending on the number of producers and what partitioning key you are using it could be that you end up with a lot of data stacked up on one partition while others have little.  What'll happen is exactly what you describe, it'll appear that some of your data is "missing" but it just hasn't been read from the partition yet.  You may want to reduce the number of consumer threads to 1 just to let it more evenly read the partitions without the threading overhead and see if you data gaps start filling.  Usually I start with one thread and see if it'll consume the whole CPU.  If it does you don't really need more threads to keep up the throughput.

**Comment by mheese** [comment]
@joekiller, we reduced the consumer threads to 1, and let's see what effect that has.

Regarding the producer: there are a number of Logstash processes on different servers that are all writing to this particular topic (which gets read again by another set of Logstash processes later on). Currently there is nothing particularly configured for the key, and we also don't care too much about the key. Ideally we'd just like it to round-robin over the partitions. It is really too bad that there is no round-robin partitioner in the library by default (like e.g. the Sarama golang library provides).

In general, I would heavily vote for an included round-robin partitioner.

Just for your information how simple the kafka output plugin is configured everywhere (replaced with example values):

```
  kafka {
    topic_id => "mytopic"
    broker_list => "server1,server2,server3"
  }
```

**Comment by joekiller** [comment]
@mheese your most recent comment is more appropriate for logstash-output-kafka but check out this discussion: http://grokbase.com/t/kafka/users/139d9q9z4h/producer-not-distributing-across-all-partitions about partition distribution. Basically if you don't have a key topic.metadata.refresh.interval.ms updates every 10 minutes and will choose a new parition then to feed to. It is much more effective to have a series of messages just flow in a stream versus fanning them out to many partitions.

I'd still really love to know what your offsets look like using:

```bash
bin/kafka-run-class.sh kafka.tools.ConsumerOffsetChecker
```

from: https://cwiki.apache.org/confluence/display/KAFKA/System+Tools#SystemTools-ConsumerOffsetChecker

**Comment by joekiller** [comment]
Closing. Please reopen if you have more information.
