### ISSUE TITLE
Add feature to attach record headers to events

### ISSUE THREAD

**Issue by Tee4151969** [logstash-plugins/logstash-input-kafka#336]
I want to read hilight in picture

![image](https://user-images.githubusercontent.com/10841479/81278172-85e75c80-907f-11ea-868b-da6205abc982.png)

**Comment by Tee4151969** [comment]
edit kafka.rb in intregration plug in kafka

**Comment by yaauie** [comment]
I've migrated this feature request to the integration plugin.
