### ISSUE TITLE
Confluent Avro - schema_registry : https and basic auth do not work

### ISSUE THREAD

**Issue by m-a-leclercq** [logstash-plugins/logstash-input-kafka#339]
**Logstash information**:

Please include the following information:

1. Logstash version 7.11.1
2. Logstash installation source:  Docker
3. How is Logstash being run:  Docker
4. How was the Logstash Plugin installed Baseline.

**JVM** (e.g. `java -version`): Bundled JDK used. 

**OS version** (`uname -a` if on a Unix-like system):   3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Mar 25 21:21:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 
logstash does not seem to be able to use https nor an user / password for the schema_registry* properties 

**Steps to reproduce**:
1 - Input.yml 
```
input {
  kafka {
        bootstrap_servers => "mybroker.kafka:9094"
        group_id => "my_group"
        client_id => "my_client"
        topics => "mytopic"
        schema_registry_url => "https://my.registry:8081/"
        schema_registry_key => "myuser"
        schema_registry_secret => "mypassword"
        codec => "json"
        decorate_events => true
        auto_offset_reset => "earliest"
        jaas_path => "/path/to/kafka-jaas-input.conf"
        sasl_mechanism => "SCRAM-SHA-512"
        security_protocol => "SASL_SSL"
        ssl_truststore_location => "/path/to/certs/my.truststore.jks"
        ssl_truststore_password => "REDACTED"
        key_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
    }
}
```

**Provide logs (if relevant)**:
[This post will tell you all about the HTTPS connection problem and its corresponding logs](https://discuss.elastic.co/t/kafka-input-avro-https-schema-registry-url-unable-to-find-valid-certification-path-to-requested-target/278438?u=malec )

[This post on SO will give you greater insight as to why authentication does not work](https://stackoverflow.com/questions/67586950/can-not-connect-logstash-to-confluent-schema-registry)
It seems like the code tries to access the registry without the basic auth credentials, and retries with credentials after it gets a 401, which seems to work for the initial connection, but creates a fatal error that restarts the pipeline once it tries to access the registry for a specific schema.

**conclusion**
After using [HaProxy as an SSL termination + having the backend pass basic auth credentials](https://discuss.elastic.co/t/kafka-input-avro-https-schema-registry-url-unable-to-find-valid-certification-path-to-requested-target/278438/2?u=malec), the pipeline works as intended.

**Comment by robbavey** [comment]
@m-a-leclercq The latest version of the logstash kafka integration plugin includes fixes that should enable this functionality to work. 

This repo is for older versions of the logstash kafka plugin before the input and output plugins were combined into a single integration plugin, the repo for which can be found [here](https://github.com/logstash-plugins/logstash-integration-kafka)

I'm going to go ahead and close this issue in this repo. If you find that the latest version of the integration plugin is still not working for you, please go ahead and open a new issue in that repo
