### ISSUE TITLE
Audit existing defaults for Kafka consumer

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-kafka#36]
Need to audit and verify if default settings makes sense with performance numbers. Especially configurations like `fetch_message_max_bytes`, `:queue_size` and `:consumer_threads`

**Comment by joekiller** [comment]
`:consumer_threads` performance is very dependent upon the partition settings for the topic and you can get thread starvation sometimes if it is too high causing it to appear like it isn't consuming anything. I've found that one thread can easily max out a CPU so I wouldn't put it much over max CPUs is not leaving it at one.

I've never seen the Kafka side of the plugin bottleneck so I'm not sure if `:queue_size` will help much unless you are doing Kafka > Logstash > Kafka or another sink other than Elasticsearch.  Perhaps I just had undersized ES clusters.

`fetch_message_max_bytes` is optimal at 1 MB.  See http://www.cloudera.com/content/cloudera/en/documentation/cloudera-kafka/latest/topics/kafka_performance.html and https://engineering.linkedin.com/kafka/benchmarking-apache-kafka-2-million-writes-second-three-cheap-machines
