### ISSUE TITLE
Logstash throws an exception upon terminating

### ISSUE THREAD

**Issue by bpatelcs** [logstash-plugins/logstash-input-kafka#38]
{:exception=>#<LogStash::ShutdownSignal: LogStash::ShutdownSignal>, :backtrace=>["org/jruby/ext/thread/SizedQueue.java:133:in `push'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-0.1.14/lib/logstash/inputs/kafka.rb:172:in `queue_event'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-codec-binary/lib/logstash/codecs/binary.rb:26:in `decode'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-0.1.14/lib/logstash/inputs/kafka.rb:163:in `queue_event'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-0.1.14/lib/logstash/inputs/kafka.rb:133:in `run'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/home/cisco/workspace/naas/naas-core/logging/third-party/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:error}

**Comment by joekiller** [comment]
Can we get the config that was running on the troubled system?

**Comment by bpatelcs** [comment]
logstash-1.5.0/bin/logstash  -e 'input{kafka {     topic_id =>”abc"     zk_connect =>"localhost:2181/kafka_main"     type=>”abc"     reset_beginning=>true     auto_offset_reset=>smallest     codec=>binary{}   }}output{ if [type]==“abc"{ file {       path =>"/home/var/dumps/abc.dump"       message_format=>"%{message}||" } }}'

**Comment by joekiller** [comment]
And you just ctrl-c to close and it'll throw the previously mentioned error?

**Comment by bpatelcs** [comment]
Yes,I do ctrl+c to stop it and it threw that error.

**Comment by joekiller** [comment]
The `codec=>binary{}` is unfamiliar.  Is that something you are using internally?

**Comment by suyograo** [comment]
@bpatelcs please reopen this issue with more info. Also you can use https://discuss.elastic.co/c/logstash for questions and debugging help. GitHub is reserved for issues and enhancements.
