### ISSUE TITLE
Stalling thread preventing closing of logstash

### ISSUE THREAD

**Issue by oazabir** [logstash-plugins/logstash-input-kafka#62]
I get this, which prevents logstash from closing: 

 {:level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"total"=>0}, "STALLING_THREADS"=>{["LogStash::Inputs::Kafka", {"zk_connect"=>"10.187.147.57:2181,10.187.147.58:2181,10.35.132.117:2181", "topic_id"=>"rsyslog_logstash2", "reset_beginning"=>"false", "type"=>"kafka"}]=>[{"thread_id"=>19, "name"=>"<kafka", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-2.0.3/lib/logstash/inputs/kafka.rb:139:in `pop'"}]}}

**Comment by jsvd** [comment]
it seems [this pop from the queue](https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L139) isn't being checked for logstash termination since it's a blocking operation.

@talevy maybe pushing a dummy event to the queue on `stop` would solve this?

**Comment by joekiller** [comment]
With the new jruby-kafka consumer design I think we can fix this. The consumption will move into a different thread and we can move some logic into the thread as @jsvd described to push a message to shutdown the process.

**Comment by joekiller** [comment]
This is the same issue as #49
