### ISSUE TITLE
Commit offsets to kafka rather than zookeeper

### ISSUE THREAD

**Issue by siddharthasahu** [logstash-plugins/logstash-input-kafka#66]
Hi,

Is it possible to change the offset commit policy to commit to kafka rather than zookeeper?
https://cwiki.apache.org/confluence/display/KAFKA/Committing+and+fetching+consumer+offsets+in+Kafka

If not, is this feature being considered?

Thanks

**Comment by suyograo** [comment]
Hey, we are rewriting this input using 0.9 consumer API which will support offset commits to Kafka. See #48

**Comment by siddharthasahu** [comment]
Moving a kafka cluster from 0.8 to 0.9 will require some effort. It would be good if logstash had support for 0.8 too.

Thanks
