### ISSUE TITLE
Provide Support for reading lz4 compressed Topics

### ISSUE THREAD

**Issue by tylerfontaine** [logstash-plugins/logstash-input-kafka#74]
Currently, when reading from an lz4 compressed topic from Kafka 0.8.2 results in the following error:

```
Kafka::Consumer caught exception: Java::KafkaCommon::UnknownCodecException
3 is an unknown compression codec
```

It appears that there is only support for reading from gzip and snappy compression for input, though lz4 seems supported in the output plugin.

**Comment by suyograo** [comment]
Thanks @joekiller I'll prep a PR
