### ISSUE TITLE
Java Event can't convert ArrayJavaProxy when decorate_events is true and key exists.

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-input-kafka#82]
Line 182 tries to set event["kafka"] to a ruby hash.
Unfortunately the key is an array of bytes. JRuby wraps this in an ArrayJavaProxy.
Java Event does not like this.

Fix: stringify the `message_and_metadata.key` in the same way as the `message_and_metadata.message`

**Comment by isayyid** [comment]
FYI, I have this reproduced in my environment and added the ArrayJavaProxy to enum structure in Javaifier.java with the following deep parser:

public static Object deep(ArrayJavaProxy a) {
        return a.getJavaArray().getValue();
}

This seems to have worked and I no longer see the error. But not sure if that is a good fix.

**Comment by guyboertje** [comment]
Readers please note:
use this workaround...
`key_decoder_class => "kafka.serializer.StringDecoder"`

**Comment by guyboertje** [comment]
Closed by 9cdb64f
