### ISSUE TITLE
auto_commit_interval_ms default should be the same as Kafka new consumer configuration default

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#90]
As part of the validation work done in https://github.com/logstash-plugins/logstash-input-kafka/issues/88 

```
auto_commit_interval_ms -> 5000 (Note:  For this one, Kafka's new default is 5000, but ours is 10)
```

The auto_commit_interval_ms default for our Kafka input plugin is set to 10, but Kafka's new consumer default for this same parameter is 5000.

**Comment by ppf2** [comment]
Current workaround until the default is fixed in the plugin is to explicitly set auto_commit_interval_ms to 5000 in the Kafka input plugin configuration.

**Comment by talevy** [comment]
This PR : #91 resolves this issue
