### ISSUE TITLE
Support Kafka 0.10 client

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#93]
Kafka 0.10 exposes a new max.poll.records setting that can help with excessive rebalancing behaviors in Kafka.

https://cwiki.apache.org/confluence/display/KAFKA/KIP-41%3A+KafkaConsumer+Max+Records

This is an enhancement request for the Kafka plugin to support Kafka 0.10 client not just to get the latest fixes but also to expose this new option via the Kafka input plugin.

**Comment by talevy** [comment]
tracking PR: https://github.com/logstash-plugins/logstash-input-kafka/pull/94

**Comment by karanpradhan** [comment]
@talevy Would this PR add SASL features to the kafka client as well ?

**Comment by suyograo** [comment]
0.10.1.x is supported in version 6.x of this plugin.
