### ISSUE TITLE
Add support  SASL/Kerberos authentication 

### ISSUE THREAD

**Issue by ESamir** [logstash-plugins/logstash-input-kafka#97]
Kafka support  SASL/Kerberos,  can you add SASL/Kerberos authentication support in the logstash-input-kafka

http://kafka.apache.org/documentation.html#security_sasl

**Comment by markdav** [comment]
Very surprised this hasn't had more upvotes - is anyone working on this?

**Comment by suyograo** [comment]
Fixed in v5.1.0
